name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_NAME: ${{secrets.DOCKER_NAME}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: debug
      run: echo $DOCKER_USER $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $(date +%s)
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_NAME}}
