# .github/workflows/docker-hub.yml
name: Docker-Hub
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        DOCKER_NAME: ${{ secrets.DOCKER_NAME }} 
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USER --password-stdin

    - name: Build docker image
      run: docker build

    - name: Push to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
        DOCKER_NAME: ${{ secrets.DOCKER_NAME }} 
      run: docker push $DOCKER_USER/$DOCKER_NAME
